#!/usr/bin/env bash
#install and configure HAproxy on my server

apt-get update
apt-get install -y haproxy

printf %s "
frontend http-in
	bind *:80
	mode http
	default_backend student_server
backend student_server
        balance roundrobin
        server 154650-web-01 100.25.103.62:80 check
	server 154650-web-02 54.237.45.129:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
